apiVersion: apps/v1
kind: Deployment
metadata:
  name: tone-api-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tone-api
  template:
    metadata:
      labels:
        app: tone-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: tone-api
          image: developer390/tone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          resources:
            requests:
              cpu: "100m"        # Request 0.1 CPU cores
              memory: "512Mi"    # Request 512 MiB of memory
            limits:
              cpu: "256m"        # Limit to 0.256 CPU cores
              memory: "1Gi"      # Set a reasonable memory limit
      imagePullSecrets:
        - name: acr-auth