apiVersion: v1
kind: Service
metadata:
  name: tone-api-service
  namespace: dev
  labels:
    app: tone-api
spec:
  selector:
    app: tone-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP